export const GET_ALLINGREDIENTS = 'GET_ALLINGREDIENTS';
export const GET_FEED_FAILED = 'GET_FEED_FAILED';
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';

export const INCREASE_COUNT = 'INCREASE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REPLACE_BUN = 'REPLACE_BUN';
export const SORT_INGREDIENT = 'SORT_INGREDIENT';

export const POST_ORDER = 'POST_ORDER';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const CLEAR_ORDER = 'CLEAR_ORDER';

export const OPEN_INGREDIENT = 'OPEN_INGREDIENT';
export const CLEAR_INGREDIENT = 'CLEAR_INGREDIENT';
