export const INCREASE_COUNT = 'INCREASE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REPLACE_BUN = 'REPLACE_BUN';
export const SORT_INGREDIENT = 'SORT_INGREDIENT';
